### ISSUE TITLE
Add support for mere text files (txt, MD, ... files)

### ISSUE THREAD

**Issue by olivmindee** [shiraji/yet-another-emoji-support#32]
Is it possible to support text files, especially .MD files? That would be very handy to have emoji support in PyCharm while writing README.MD or CHANGELOG.MD files. Thanks!

**Comment by shiraji** [comment]
Thanks for reporting issue! You are the first for this plugin 😉Now, this plugin should already support markdown. 

Questions:
1. Did you install [markdown plugin](https://plugins.jetbrains.com/plugin/7793-markdown) in PyCharm?
1. Which version of markdown plugin are you using?
1. Which version of PyCharm are you using?

**Comment by shiraji** [comment]
I reproduced this issue. Let me check.

**Comment by shiraji** [comment]
Should fix by 1.0.3.

If you still observe the same problem, please feel free to reopen this issue.

Thanks for reporting!
