### ISSUE TITLE
WebStorm 2019.2.2, works only in commit messages

### ISSUE THREAD

**Issue by GrayStrider** [shiraji/yet-another-emoji-support#53]

**Comment by shiraji** [comment]
Which language or file type did you use?

**Comment by shiraji** [comment]
@GrayStrider 

![image](https://user-images.githubusercontent.com/3675458/66269650-ca124480-e885-11e9-8af6-d12070e5dde2.png)

It seems working to me. I cannot use 2019.2.2 because the version has a terrible bug with Japanese IDE.

```
WebStorm 2019.2.3
Build #WS-192.6817.13, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 8
Registry: 
Non-Bundled Plugins: com.github.shiraji.yaemoji
```

**Comment by GrayStrider** [comment]
Oh, I'm very sorry; I had to initiate it with Ctrl + Space; I'm used to that occuring automatically.
