### ISSUE TITLE
Not working with WebStorm 2019.3.1, is it compatible?

### ISSUE THREAD

**Issue by vladgalindo** [shiraji/yet-another-emoji-support#55]
The pluging is not working anymore on the latest upgrades, i tried on several ways
`WebStorm 2019.3.1
Build #WS-193.5662.54, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1502M
Cores: 4`
this is my pc details if it helps on something...

**Comment by shiraji** [comment]
let me check

**Comment by shiraji** [comment]
My environment is here and it works fine.

```
WebStorm 2019.3.2
Build #WS-193.6015.40, built on January 21, 2020
Licensed to "my name"
Subscription is active until "someday"
Runtime version: 11.0.5+10-b520.30 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: com.github.shiraji.yaemoji
```

![スクリーンショット 2020-01-25 2 52 27](https://user-images.githubusercontent.com/3675458/73091474-dba75700-3f1d-11ea-9e40-1adcefc8700f.png)

Do you have any logs or error messages?

**Comment by zechaos031** [comment]
try ctrl + space when you mark your emoji

Ex: :car and made ctrl + space ^^

**Comment by vladgalindo** [comment]
> try ctrl + space when you mark your emoji
> 
> Ex: :car and made ctrl + space ^^

@zechaos031 thanks a lot that did the trick!!
