### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by asyba** [shiraji/yet-another-emoji-support#56]
I just installed you plugin, but almost all icons are not displayed.
Do I need something else to install?

![image](https://user-images.githubusercontent.com/1466530/73123859-72eac980-3f73-11ea-959f-363a9844ea9d.png)

System:
Ubuntu 18.10
IntelliJ IDEA Ultimate  2019.3.2 Build #IU-193.6015.39

**Comment by shiraji** [comment]
No, see https://github.com/shiraji/yet-another-emoji-support/issues/54

vote up
https://youtrack.jetbrains.com/issue/IDEA-168570
https://youtrack.jetbrains.com/issue/JBR-11

**Comment by asyba** [comment]
But my issue is in Ubuntu not Windows...

**Comment by shiraji** [comment]
https://youtrack.jetbrains.com/issue/IDEA-192107

**Comment by shiraji** [comment]
https://youtrack.jetbrains.com/issue/IDEA-192107#focus=streamItem-27-2888997.0-0

> At the moment our IDEs don't support color emojis on Windows and Linux.

**Comment by asyba** [comment]
> https://youtrack.jetbrains.com/issue/IDEA-192107#focus=streamItem-27-2888997.0-0
> 
> > At the moment our IDEs don't support color emojis on Windows and Linux.

:(
