### ISSUE TITLE
Unsupported fonts?

### ISSUE THREAD

**Issue by constown** [shiraji/yet-another-emoji-support#65]
now:

use fonts: jetbrains mono

![3620377ecbbc89117fe808f8a883e3c](https://user-images.githubusercontent.com/50108901/102329457-645e3400-3fc3-11eb-91a3-b0a57a6da56c.png)

wish:

![image](https://user-images.githubusercontent.com/50108901/102329590-89eb3d80-3fc3-11eb-9f77-a335cfd5d4d0.png)

**Comment by constown** [comment]
windows10

**Comment by carldressler** [comment]
I am facing the same issue.

**Comment by TheShwarma** [comment]
same issue

**Comment by shiraji** [comment]
see https://github.com/shiraji/yet-another-emoji-support/issues/54#issuecomment-578231710
